const STORE_TYPE_LIST = 'list';

export const LOAD_ADDRESS_LIST = `${STORE_TYPE_LIST}/LOAD_ADDRESS_LIST`;
export const LOAD_ADDRESS_LIST_SUCCESS = `${STORE_TYPE_LIST}/LOAD_ADDRESS_LIST_SUCCESS`;
export const LOAD_ADDRESS_LIST_FAILURE = `${STORE_TYPE_LIST}/LOAD_ADDRESS_LIST_FAILURE`;

const STORE_TYPE_ROUTE = 'route';

export const CREATE_ROUTE = `${STORE_TYPE_ROUTE}/CREATE_ROUTE`;
export const CREATE_ROUTE_SUCCESS = `${STORE_TYPE_ROUTE}/CREATE_ROUTE_SUCCESS`;
export const CREATE_ROUTE_FAILURE = `${STORE_TYPE_ROUTE}/CREATE_ROUTE_FAILURE`;
