const STORE_TYPE = 'card';

export const SAVE_CARD = `${STORE_TYPE}/SAVE_CARD`;
export const SAVE_CARD_SUCCESS = `${STORE_TYPE}/SAVE_CARD_SUCCESS`;
export const SAVE_CARD_FAILURE = `${STORE_TYPE}/SAVE_CARD_FAILURE`;

export const GET_CARD = `${STORE_TYPE}/GET_CARD`;
export const GET_CARD_SUCCESS = `${STORE_TYPE}/GET_CARD_SUCCESS`;
export const GET_CARD_FAILURE = `${STORE_TYPE}/GET_CARD_FAILURE`;
